# Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
df = pd.read_csv("globalterrorismdb_0718dist.csv", low_memory=False, encoding="latin-1")
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [5]:
df.shape

(181691, 135)

In [10]:
df['eventid'].unique().shape

(181691,)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181691 entries, 0 to 181690
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 187.1+ MB

In [13]:
df.isnull().sum()

eventid            0
iyear              0
imonth             0
iday               0
approxdate    172452
               ...
INT_LOG            0
INT_IDEO           0
INT_MISC           0
INT_ANY            0
related       156653
Length: 135, dtype: int64

In [14]:
df.dropna(axis=1 , inplace=True)

In [15]:
df.shape

(181691, 29)

In [16]:
df

,eventid,iyear,imonth,iday,extended,country,country_txt,region,region_txt,vicinity,...,gname,individual,weaptype1,weaptype1_txt,property,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
0,197000000001,1970,7,2,0,58,Dominican Republic,2,Central America & Caribbean,0,...,MANO-D,0,13,Unknown,0,PGIS,0,0,0,0
1,197000000002,1970,0,0,0,130,Mexico,1,North America,0,...,23rd of September Communist League,0,13,Unknown,0,PGIS,0,1,1,1
2,197001000001,1970,1,0,0,160,Philippines,5,Southeast Asia,0,...,Unknown,0,13,Unknown,0,PGIS,-9,-9,1,1
3,197001000002,1970,1,0,0,78,Greece,8,Western Europe,0,...,Unknown,0,6,Explosives,1,PGIS,-9,-9,1,1
4,197001000003,1970,1,0,0,101,Japan,4,East Asia,0,...,Unknown,0,8,Incendiary,1,PGIS,-9,-9,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,201712310022,2017,12,31,0,182,Somalia,11,Sub-Saharan Africa,0,...,Al-Shabaab,0,5,Firearms,-9,START Primary Collection,0,0,0,0
181687,201712310029,2017,12,31,0,200,Syria,10,Middle East & North Africa,1,...,Muslim extremists,0,6,Explosives,1,START Primary Collection,-9,-9,1,1
181688,201712310030,2017,12,31,0,160,Philippines,5,Southeast Asia,0,...,Bangsamoro Islamic Freedom Movement (BIFM),0,8,Incendiary,1,START Primary Collection,0,0,0,0
181689,201712310031,2017,12,31,0,92,India,6,South Asia,0,...,Unknown,0,6,Explosives,-9,START Primary Collection,-9,-9,0,-9
181690,201712310032,2017,12,31,0,160,Philippines,5,Southeast Asia,0,...,Unknown,0,6,Explosives,0,START Primary Collection,-9,-9,0,-9

In [19]:
df.columns.values

array(['eventid', 'iyear', 'imonth', 'iday', 'extended', 'country',
       'country_txt', 'region', 'region_txt', 'vicinity', 'crit1',
       'crit2', 'crit3', 'success', 'suicide', 'attacktype1',
       'attacktype1_txt', 'targtype1', 'targtype1_txt', 'gname',
       'individual', 'weaptype1', 'weaptype1_txt', 'property', 'dbsource',
       'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY'], dtype=object)

In [25]:
df.rename(columns={'iyear':'Year','imonth':'Month','iday':"day",'gname':'Group','country_txt':'Country','region_txt':'Region','provstate':'State','city':'City','latitude':'latitude',
'longitude':'longitude','summary':'summary','attacktype1_txt':'Attacktype','targtype1_txt':'Targettype','weaptype1_txt':'Weapon','nkill':'kill',
'nwound':'Wound'},inplace=True)

In [26]:
df.columns.values

array(['eventid', 'Year', 'Month', 'day', 'extended', 'country',
       'Country', 'region', 'Region', 'vicinity', 'crit1', 'crit2',
       'crit3', 'success', 'suicide', 'attacktype1', 'Attacktype',
       'targtype1', 'Targettype', 'Group', 'individual', 'weaptype1',
       'Weapon', 'property', 'dbsource', 'INT_LOG', 'INT_IDEO',
       'INT_MISC', 'INT_ANY'], dtype=object)

In [27]:
df.shape

(181691, 29)

In [28]:
df.corr()

,eventid,Year,Month,day,extended,country,region,vicinity,crit1,crit2,...,suicide,attacktype1,targtype1,individual,weaptype1,property,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
eventid,1.000000,0.999996,0.002706,0.018336,0.091761,-0.135039,0.401371,0.070646,0.002019,0.026215,...,0.137743,0.074173,0.079080,0.017939,-0.011716,-0.278927,-0.143600,-0.133252,-0.077852,-0.175605
Year,0.999996,1.000000,0.000139,0.018254,0.091754,-0.135023,0.401384,0.070659,0.001995,0.026211,...,0.137736,0.074153,0.079082,0.017944,-0.011737,-0.278916,-0.143601,-0.133253,-0.077847,-0.175596
Month,0.002706,0.000139,1.000000,0.005497,-0.000468,-0.006305,-0.002999,-0.004501,0.001568,0.001734,...,0.003071,0.006705,-0.000948,-0.001661,0.007863,-0.005816,-0.002302,-0.002034,-0.002554,-0.006336
day,0.018336,0.018254,0.005497,1.000000,-0.004700,0.003468,0.009710,-0.005367,0.011434,-0.002702,...,0.003593,-0.005333,-0.000052,-0.003788,-0.003019,-0.003903,-0.001540,-0.001621,-0.002027,-0.001199
extended,0.091761,0.091754,-0.000468,-0.004700,1.000000,-0.020466,0.038389,0.017784,-0.015029,0.001249,...,-0.033961,0.272272,0.011613,-0.008929,0.207802,-0.002096,0.071768,0.075147,0.027335,0.080767
country,-0.135039,-0.135023,-0.006305,0.003468,-0.020466,1.000000,0.148597,-0.012291,-0.006646,-0.038480,...,-0.050360,-0.021384,-0.019703,0.027918,-0.023708,0.032051,0.069904,0.067564,0.207281,0.153118
region,0.401371,0.401384,-0.002999,0.009710,0.038389,0.148597,1.000000,0.073678,0.025521,-0.013163,...,0.112672,0.007642,0.041396,-0.059963,0.013257,-0.183279,-0.082584,-0.071917,0.043139,-0.047900
vicinity,0.070646,0.070659,-0.004501,-0.005367,0.017784,-0.012291,0.073678,1.000000,0.003330,-0.000534,...,0.008352,0.006504,0.024644,-0.011986,0.001496,-0.019811,0.014487,0.015119,-0.008232,0.010325
crit1,0.002019,0.001995,0.001568,0.011434,-0.015029,-0.006646,0.025521,0.003330,1.000000,-0.008984,...,0.019039,0.027544,-0.040026,-0.025591,0.029257,-0.007595,0.089973,0.089888,0.015692,0.082288
crit2,0.026215,0.026211,0.001734,-0.002702,0.001249,-0.038480,-0.013163,-0.000534,-0.008984,1.000000,...,0.002770,0.005157,-0.101522,0.003311,-0.008549,-0.002711,-0.024153,-0.023829,-0.012980,-0.027752
crit3,-0.016789,-0.016784,0.000176,-0.004889,0.048533,-0.040288,-0.010175,-0.054995,-0.040589,-0.031425,...,-0.026620,0.028124,0.251296,0.016806,0.018320,0.013345,-0.134557,-0.138251,-0.036112,-0.130216
success,-0.082972,-0.082963,-0.002845,-0.011802,0.073233,-0.037827,-0.030909,-0.002223,-0.010733,-0.013476,...,-0.031155,0.048408,-0.059637,-0.013868,-0.008178,-0.036876,0.059875,0.059183,-0.014906,0.038245
suicide,0.137743,0.137736,0.003071,0.003593,-0.033961,-0.050360,0.112672,0.008352,0.019039,0.002770,...,1.000000,-0.029962,-0.023440,0.000775,-0.039928,-0.073382,0.058735,0.065882,-0.000879,0.057241
attacktype1,0.074173,0.074153,0.006705,-0.005333,0.272272,-0.021384,0.007642,0.006504,0.027544,0.005157,...,-0.029962,1.000000,0.014513,0.016438,0.658954,0.031976,0.075002,0.077225,0.010632,0.088711
targtype1,0.079080,0.079082,-0.000948,-0.000052,0.011613,-0.019703,0.041396,0.024644,-0.040026,-0.101522,...,-0.023440,0.014513,1.000000,0.005267,0.019846,0.004897,-0.056550,-0.058010,-0.043492,-0.054497
individual,0.017939,0.017944,-0.001661,-0.003788,-0.008929,0.027918,-0.059963,-0.011986,-0.025591,0.003311,...,0.000775,0.016438,0.005267,1.000000,0.005754,0.006625,-0.048526,-0.048542,0.005490,-0.037488
weaptype1,-0.011716,-0.011737,0.007863,-0.003019,0.207802,-0.023708,0.013257,0.001496,0.029257,-0.008549,...,-0.039928,0.658954,0.019846,0.005754,1.000000,0.018999,0.072941,0.074702,-0.011652,0.084257
property,-0.278927,-0.278916,-0.005816,-0.003903,-0.002096,0.032051,-0.183279,-0.019811,-0.007595,-0.002711,...,-0.073382,0.031976,0.004897,0.006625,0.018999,1.000000,0.052445,0.047609,0.022058,0.065701
INT_LOG,-0.143600,-0.143601,-0.002302,-0.001540,0.071768,0.069904,-0.082584,0.014487,0.089973,-0.024153,...,0.058735,0.075002,-0.056550,-0.048526,0.072941,0.052445,1.000000,0.996211,0.052537,0.891051
INT_IDEO,-0.133252,-0.133253,-0.002034,-0.001621,0.075147,0.067564,-0.071917,0.015119,0.089888,-0.023829,...,0.065882,0.077225,-0.058010,-0.048542,0.074702,0.047609,0.996211,1.000000,0.082014,0.893811
INT_MISC,-0.077852,-0.077847,-0.002554,-0.002027,0.027335,0.207281,0.043139,-0.008232,0.015692,-0.012980,...,-0.000879,0.010632,-0.043492,0.005490,-0.011652,0.022058,0.052537,0.082014,1.000000,0.252193
INT_ANY,-0.175605,-0.175596,-0.006336,-0.001199,0.080767,0.153118,-0.047900,0.010325,0.082288,-0.027752,...,0.057241,0.088711,-0.054497,-0.037488,0.084257,0.065701,0.891051,0.893811,0.252193,1.000000

In [31]:
df.to_csv('data_cleaed.csv')

# From The Dashboard Made By Power BI

## Conclusion

1- Middle East Is Most Effected Region 
2- Iraq Is The Mosst Effected Country
3- 2014 Is The Most Year With Attacks
4- The Number Of Attacks Started To Increase After 2012
5- Blombing/Explosion Is The Most Type Used By Attackers
6- The Most Attacks are Unkown Who Port It But Taliban Is The Most Group With Attacks 
7- Private Citizens & Property Is The Most Attack Type
8- Explosives Is The Most Weapon Used In Attacks

Thanks